ALTER TABLE `attendances`
  CHANGE COLUMN `task_begin_at` `task_begin_at` DATETIME NULL DEFAULT NULL ,
  CHANGE COLUMN `task_end_at` `task_end_at` DATETIME NULL DEFAULT NULL ,
  CHANGE COLUMN `register_at` `register_at` DATETIME NULL DEFAULT NULL ,
  CHANGE COLUMN `create_at` `create_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'CURRENT_TIMESTAMP' ,
  CHANGE COLUMN `update_at` `update_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
  CHANGE COLUMN `delete_at` `delete_at` DATETIME NULL DEFAULT NULL ,
  CHANGE COLUMN `active` `active` TINYINT(1) NULL DEFAULT '1' ,
  CHANGE COLUMN `deleted` `deleted` TINYINT(1) NULL DEFAULT '0' ,
  ADD COLUMN `staff_id` BIGINT(20) NULL DEFAULT NULL AFTER `register_by`;
