ALTER TABLE `regular_evaluations`
  CHANGE COLUMN `delete_by` `delete_by` BIGINT(20) NULL DEFAULT NULL COMMENT '删除者' AFTER `update_at`,
  CHANGE COLUMN `delete_at` `delete_at` DATETIME NULL DEFAULT NULL COMMENT '删除时间' AFTER `delete_by`,
  CHANGE COLUMN `evaluation_content` `evaluation_content` VARCHAR(200) NULL DEFAULT NULL COMMENT '考核内容' ,
  CHANGE COLUMN `create_at` `create_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' ,
  CHANGE COLUMN `update_at` `update_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间' ,
  CHANGE COLUMN `active` `active` TINYINT(1) NULL DEFAULT '1' COMMENT '激活标记' ,
  CHANGE COLUMN `deleted` `deleted` TINYINT(1) NULL DEFAULT '0' COMMENT '删除标记' ,
  ADD COLUMN `evaluated_at` DATE NULL AFTER `evaluation_subject`,
  ADD COLUMN `state` VARCHAR(45) NULL AFTER `evaluator`,
  ADD COLUMN `device_count` VARCHAR(45) NULL AFTER `state`,
  ADD COLUMN `finishing_rate` VARCHAR(45) NULL AFTER `device_count`,
  ADD COLUMN `working_score` VARCHAR(45) NULL AFTER `finishing_rate`,
  ADD COLUMN `client_score` VARCHAR(45) NULL AFTER `working_score`,
  ADD COLUMN `all_score` VARCHAR(45) NULL AFTER `client_score`;
