ALTER TABLE `power_broker`.`users`
  ADD COLUMN `create_by` BIGINT(20) NULL AFTER `password`,
  ADD COLUMN `create_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER `create_by`,
  ADD COLUMN `update_by` BIGINT(20) NULL AFTER `create_at`,
  ADD COLUMN `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `update_by`,
  ADD COLUMN `delete_by` BIGINT(20) NULL AFTER `update_at`,
  ADD COLUMN `delete_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER `delete_by`,
  ADD COLUMN `active` TINYINT(1) NULL DEFAULT '1' AFTER `delete_at`,
  ADD COLUMN `deleted` TINYINT(1) NULL DEFAULT '0' AFTER `active`;

ALTER TABLE `power_broker`.`roles`
  ADD COLUMN `create_by` BIGINT(20) NULL AFTER `name`,
  ADD COLUMN `create_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER `create_by`,
  ADD COLUMN `update_by` BIGINT(20) NULL AFTER `create_at`,
  ADD COLUMN `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `update_by`,
  ADD COLUMN `delete_by` BIGINT(20) NULL AFTER `update_at`,
  ADD COLUMN `delete_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER `delete_by`,
  ADD COLUMN `active` TINYINT(1) NULL DEFAULT '1' AFTER `delete_at`,
  ADD COLUMN `deleted` TINYINT(1) NULL DEFAULT '0' AFTER `active`;

ALTER TABLE `power_broker`.`client_details`
  ADD COLUMN `create_by` BIGINT(20) NULL AFTER `auto_approve`,
  ADD COLUMN `create_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER `create_by`,
  ADD COLUMN `update_by` BIGINT(20) NULL AFTER `create_at`,
  ADD COLUMN `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `update_by`,
  ADD COLUMN `delete_by` BIGINT(20) NULL AFTER `update_at`,
  ADD COLUMN `delete_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER `delete_by`,
  ADD COLUMN `active` TINYINT(1) NULL DEFAULT '1' AFTER `delete_at`,
  ADD COLUMN `deleted` TINYINT(1) NULL DEFAULT '0' AFTER `active`;