ALTER TABLE `enterprises`
  CHANGE COLUMN `create_at` `create_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'CURRENT_TIMESTAMP' ,
  CHANGE COLUMN `update_at` `update_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
  CHANGE COLUMN `delete_at` `delete_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ,
  CHANGE COLUMN `active` `active` TINYINT(1) NULL DEFAULT '1' ,
  CHANGE COLUMN `deleted` `deleted` TINYINT(1) NULL DEFAULT '0' ;