ALTER TABLE `warning_logs`
  CHANGE COLUMN `update_at` `update_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
  CHANGE COLUMN `delete_at` `delete_at` DATETIME NULL DEFAULT NULL ;

ALTER TABLE `event_logs`
  CHANGE COLUMN `update_at` `update_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
  CHANGE COLUMN `delete_at` `delete_at` DATETIME NULL DEFAULT NULL ;