spring:
  application:
    name: microservice-discovery
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
management:
  security:
    enabled: false
---
spring:
  profiles: peer1

server:
  port: 8761

eureka:
  instance:
    hostname: service.discovery.peer1
  client:
    serviceUrl:
      defaultZone: http://service.discovery.peer2:8762/eureka/

---
spring:
  profiles: peer2

server:
  port: 8762

eureka:
  instance:
    hostname: service.discovery.peer2
  client:
    serviceUrl:
      defaultZone: http://service.discovery.peer1:8761/eureka/