gps:
    auth:
        uri: /1/auth/access_token
    gataway:
        host: http://api.gpsoo.net
    tracking:
        uri: /1/devices/tracking
logger:
    charset: UTF-8
    file: pb-resource-server
    max:
        file:
            size: 30MB
        history: 30
    path: /tmp/log/pb/pb-resource-server
    pattern: '[%d{yyyyMMdd HHmmss.SSS} %X{identify}] - [%thread %logger{30}] - [%msg]%n'
security:
    basic:
      enabled: false
    filter-order: 2
server:
    contextPath: /module-administration
    port: 3884
spring:
    application:
        name: Resource Api
    data:
        mongodb:
            database: pb
            authentication-database: pb
            host: mongo1.36355888.top
            port: 27017
            password: qwer1234
            username: pb_root
#            uri: "mongodb://pb_root:qwer1234@staging.mongo1.36355888.top,staging.mongo2.36355888.top,staging.mongo3.36355888.top/pb"
    redis:
        host: staging.redis.36355888.top
        password: Zhongxin2017good!#
        database: 1
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1
          min-idle: 0
          test-on-return: true
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: power_broker
        tomcat:
            initial-size: 20
            max-active: 50
            max-wait: 28800
            test-on-borrow: true
            test-on-return: true
            test-while-idle: true
            validation-query: SELECT 1
        url: jdbc:mysql://staging.db.36355888.top:3306/power_broker?characterEncoding=utf-8&useSSL=false
        username: power_broker
    jackson:
        default-property-inclusion: non_null
    jpa:
        show-sql: true
        hibernate:
          naming:
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
          ddl-auto: validate
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
            format_sql: true
endpoints:
  cors:
    allowed-headers: '*'
    allowed-methods: POST,GET,DELETE,PUT
    allowed-origins: content-type,access-control-request-headers,access-control-request-method,accept,origin,authorization,x-requested-with
    max-age: 3600
