endpoints:
  health:
    sensitive: false
  shutdown:
    enabled: true
    sensitive: false
security:
  basic:
    enabled: false
server:
#  contextPath: /pb-spring-boot-admin
  port: 8090
spring:
  application:
    name: spring-boot-admin-web
  boot:
    admin:
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      context-path: /pb-spring-boot-admin
  jackson:
    serialization:
      indent_output: true
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://service.discovery.peer1:8761/eureka/,http://service.discovery.peer2:8762/eureka}
management:
  security:
    enabled: false